# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "whu-lyh"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Kinematic Mapping":
        filters: ["Kinematic Mapping", "Trajectory Estimation", 
                  "Trajectory Estimation", "Dynamic Networks"]
    "Map fusion":
        filters:["Map fusion", "Map merging"]
    "MultiModality":
        filters: ["Multimodel", "Multi-Modality", "Cross-Modality", "Cross-Modality",
                "Multi model", "Multi Modality", "Cross Modality", "Cross Modality", "Point Cloud image fusion"]
    "Point Cloud Localization":
        filters: ["Point Cloud Localization", "Cross matching", 
                  "Point Cloud Re-localisation", "Point cloud image registraction",
                  "Point cloud image matching", "Point cloud image alignment"]
    "Place Recognization":
        filters: ["Place Recognization", "Loop Closure Detection", "Point Cloud retrieval"]
    "LiDAR SLAM": 
        filters: ["LiDAR SLAM", "Laser Odometry", "Mapping"]
    "Transformer":
        filters: ["Transformer", "Point Cloud Transformer", "Point Transformer"]
    "NeRF":
        filters: ["NeRF"]
