# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Vincentqyw"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 20

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Visual Localization":
        filters: ["Visual Localization", "Camera Localization", "Image Localization",
                  "Camera Re-localisation", "Geolocalization", "Cross-view Geolocalization",
                  "visual place recognition", "image retrieval"]
    "Point Cloud Place Recognition":
        filters: ["Point Cloud Place Recognition", "LiDAR Place Recognition", "Point Cloud Localization", ]
    "Cross-modality Localization":
        filters: ["Cross-modality Coarse Localization", "Cross-modality Localization", "Cross-modal Localization"]
    "3D GS":
        filters: ["Gaussian Splatting", "Gaussian SLAM", "Rendering Images", "GS SLAM", "Rendering Localization"]
    "MoE":
        filters: ["Mixture of Experts", "MoE"]
    "Mamba":
        filters: ["Point Cloud Mamba", "Visual Mamba", "State Space Model"]
    "Autonomous Driving":
        filters: ["Autonomous Driving", "Autonomous Scenario"]
    "HSI Classification":
        filters: ["Hyperspectral and LiDAR Classification", "Hyperspectral Image Classification", "HSI"]
    "Map":
        filters: ["Map Fusion", "Map Representation", "Map Correction", "Map Reference"]
    "Non-rigid Registration":
        filters: ["Non-rigid Registration", "Nonrigid Registration"]

